#!/usr/bin/env bash
# install.sh — Cross-platform installer for regex-helper-skill
# Generated by agent-skill-creator

set -euo pipefail

SKILL_NAME="regex-helper-skill"
SKILL_DIR="$(cd "$(dirname "$0")" && pwd)"

# Auto-detect platform and install path
detect_and_install() {
    local platform="$1"

    case "$platform" in
        claude)
            local target="$HOME/.claude/skills/$SKILL_NAME"
            ;;
        universal)
            local target="$HOME/.agents/skills/$SKILL_NAME"
            ;;
        cursor-project)
            local target=".cursor/rules/$SKILL_NAME"
            ;;
        cursor-user)
            local target="$HOME/.cursor/rules/$SKILL_NAME"
            ;;
        copilot)
            local target=".github/skills/$SKILL_NAME"
            ;;
        windsurf-project)
            local target=".windsurf/rules/$SKILL_NAME"
            ;;
        windsurf-user)
            local target="$HOME/.windsurf/rules/$SKILL_NAME"
            ;;
        cline)
            local target=".clinerules/$SKILL_NAME"
            ;;
        codex)
            local target="$HOME/.agents/skills/$SKILL_NAME"
            ;;
        gemini)
            local target="$HOME/.gemini/skills/$SKILL_NAME"
            ;;
        kiro)
            local target=".kiro/skills/$SKILL_NAME"
            ;;
        trae)
            local target=".trae/rules/$SKILL_NAME"
            ;;
        goose)
            local target="$HOME/.config/goose/skills/$SKILL_NAME"
            ;;
        opencode)
            local target="$HOME/.config/opencode/skills/$SKILL_NAME"
            ;;
        roo-code)
            local target=".roo/rules/$SKILL_NAME"
            ;;
        antigravity)
            local target=".agents/skills/$SKILL_NAME"
            ;;
        *)
            echo "未知平台: $platform"
            return 1
            ;;
    esac

    echo "安装到: $target"
    rm -rf "$target"
    cp -R "$SKILL_DIR" "$target"
    echo "安装完成！"
    echo ""
    echo "在新会话中输入以下命令使用："
    echo "  /regex-helper-skill 帮我分析这个预设的标签"
    echo "  /regex-helper-skill 生成一个清除多余内容的正则"
}

# Auto-detect
auto_detect() {
    if [ -d "$HOME/.claude" ]; then
        detect_and_install "claude"
    elif [ -d ".cursor" ] || [ -d "$HOME/.cursor" ]; then
        detect_and_install "cursor-project"
    elif [ -d ".github" ]; then
        detect_and_install "copilot"
    elif [ -d ".windsurf" ] || [ -d "$HOME/.windsurf" ]; then
        detect_and_install "windsurf-project"
    elif [ -d ".clinerules" ]; then
        detect_and_install "cline"
    elif [ -d "$HOME/.gemini" ]; then
        detect_and_install "gemini"
    elif [ -d ".kiro" ]; then
        detect_and_install "kiro"
    elif [ -d ".trae" ]; then
        detect_and_install "trae"
    elif [ -d "$HOME/.config/goose" ]; then
        detect_and_install "goose"
    elif [ -d ".roo" ]; then
        detect_and_install "roo-code"
    elif [ -d ".agents" ] || [ -d "$HOME/.agents" ]; then
        detect_and_install "universal"
    else
        detect_and_install "universal"
    fi
}

# Parse arguments
PLATFORM=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --platform)
            PLATFORM="$2"
            shift 2
            ;;
        --all)
            echo "安装到所有检测到的平台..."
            auto_detect
            exit 0
            ;;
        --help|-h)
            echo "用法: ./install.sh [--platform <name>] [--all]"
            echo ""
            echo "支持的平台:"
            echo "  claude, universal, cursor-project, cursor-user, copilot"
            echo "  windsurf-project, windsurf-user, cline, codex, gemini"
            echo "  kiro, trae, goose, opencode, roo-code, antigravity"
            exit 0
            ;;
        *)
            echo "未知参数: $1"
            exit 1
            ;;
    esac
done

if [ -n "$PLATFORM" ]; then
    detect_and_install "$PLATFORM"
else
    auto_detect
fi
